version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: cso-db
    restart: always
    environment:
      POSTGRES_DB: cso_nickname_tracker
      POSTGRES_USER: cso_user
      POSTGRES_PASSWORD: cso_pass
    ports:
      - "5432:5432" # 필요하면 외부에서 DB 접속할 때 사용, 안 쓸 거면 주석 처리 가능
    volumes:
      - cso_db_data:/var/lib/postgresql/data
    networks:
      - cso-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cso-app
    restart: always
    depends_on:
      - db
    environment:
      # Spring datasource
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cso_nickname_tracker
      DB_USERNAME: cso_user
      DB_PASSWORD: cso_pass

      # Discord
      TOKEN: "${TOKEN}"

      # Web base URL (EC2 퍼블릭 IP / 도메인)
      APP_WEB_BASE_URL: "http://${EC2_PUBLIC_IP}:8128"
    ports:
      - "8128:8128"
    networks:
      - cso-net

networks:
  cso-net:

volumes:
  cso_db_data:
