spring:
  application:
    name: CSO-NICKNAME-TRACKER
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

discord:
  bot:
    token: ${TOKEN}

server:
  port: 8128

app:
  web-base-url: ${EXTERNAL_URL}

jackson:
  serialization:
    fail-on-empty-beans: false
